version: 2
jobs:
  build:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - cargo-cache-{{ arch }}-{{ checksum "dev/install" }}
      - run: ./dev/install
      - run: ./dev/ci
      - persist_to_workspace:
          root: .
          paths:
            - book
            - dev
      - save_cache:
          paths:
            - /usr/local/cargo/bin/mdbook
          key: cargo-cache-{{ arch }}-{{ checksum "dev/install" }}
  deploy:
    docker:
      - image: circleci/rust:latest
    steps:
      - attach_workspace:
          at: .
      - add_ssh_keys:
          # find the key from CirclCi project settings > SSH Keys > Additional SSH Keys
          # you also need to set this as a deploy key in Github repo
          # for a new one, use: `ssh-keygen -t rsa -b 4096 -C "musings.tommilligan@circleci.com" -f key -m pem`
          fingerprints:
            - "cd:cf:ac:cd:ca:41:3a:99:bf:73:f3:ba:18:5b:28:f3"
      - run: ./dev/gh-pages
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
